### ISSUE TITLE
sqrt math function not working

### ISSUE THREAD

**Issue by cedeckovec** [underverk/SmartWatch#1]
Hi all

when use sqrt math function compiler generate error

many thanks fix it

**Comment by underverk** [comment]
This has been fixed.
We were not linking against libm (math library)

You will need to download the latest SmartWatch_Toolchain and replace your underchain (smartwatch-ide/tools/underchain) or replicate the changes manually - see the following link.

https://github.com/underverk/SmartWatch_Toolchain/commit/131cc27729133faa4e1b3525fa6b7cd49f09c151
