### ISSUE TITLE
Latest Installation how-to is incomplete

### ISSUE THREAD

**Issue by Lycaonj** [underverk/SmartWatch#10]
I went through the entire installation steps for Windows and got every step done; however, when trying to compile/push one of the examples, I get an error:

java.io.IOException: Cannot run program "C:\Users\James\Desktop\smartwatch-ide-002\hardware/tools/avr/bin/avrdude": CreateProcess error=2, The system cannot find the file specified
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:459)

The zip file is apparently missing the entire ./hardware/tools/avr folder and all of the associated files.

I tried the latest stable version of avrdude from arduino.cc (1.5) and it has no DFU programmer support.  I also tried their beta (1.5.2) with the same result.  

How exactly are you guys getting your firmware onto the watch without DFU support in avrdude?

**Comment by stg** [comment]
avrdude is only used for avr microcontrollers.
the smartwatch uses an stm32f4.
for the stm32f4 target we use dfuutil.

the IDE still needs some work and may report a few incorrect error messages.
