### ISSUE TITLE
I cant make a programm!

### ISSUE THREAD

**Issue by Kossssss** [underverk/SmartWatch#11]
When I pressed make it sad:  
This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
Arduino: alpha-0001 (Windows 7), Board: "Sony SmartWatch"
tools/underchain/

make: Entering directory `C:/Users/685F~1/AppData/Local/Temp/build7151614392480847145.tmp'
Cleaning project:
rm -rf bin
make: Leaving directory`C:/Users/685F~1/AppData/Local/Temp/build7151614392480847145.tmp'
now: C:\Users\685F~1\AppData\Local\Temp\build7151614392480847145.tmp is shinny

[make, -C, C:\Users\685F~1\AppData\Local\Temp\build7151614392480847145.tmp, sketch]

make: Entering directory `C:/Users/685F~1/AppData/Local/Temp/build7151614392480847145.tmp'
c:\FPC\2.6.0\bin\i386-Win32\rm.exe: bin/src: is a directory
make: *** [touchmain] Error 1
make: Leaving directory`C:/Users/685F~1/AppData/Local/Temp/build7151614392480847145.tmp'
make вернул 2

**Comment by stg** [comment]
Did you check out the submodules?
There is information on how to do this in the README.
