### ISSUE TITLE
BT Stack?

### ISSUE THREAD

**Issue by Lycaonj** [underverk/SmartWatch#8]
Poked around but didn't see any references to the BT stack.  Is it in yet? :)  And sorry about asking questions in the issue section, there's no discussion area/forums on github :(

**Comment by ihavespoons** [comment]
I would also be interested in details about the BT stack. Once again, no discussion area.

**Comment by stg** [comment]
Why not set up a discussion somewhere and let us know about it and I will make a link in the main README.

**Comment by underverk** [comment]
yeah, there is plenty of forum systems, we need collaborators for this
project, I would be glad if you suggested a place and we would just link to
it.

/d
